_core:
  default_config_hash: 0q05ESSjlfR5LASPlCbPg0lVHAOI6fAJJAQcnMbnLdc
langcode: es
iconset: social-icons--square
services:
  facebook: facebook
  x: x
  whatsapp: whatsapp
  facebook_messenger: facebook_messenger
  email: email
  pinterest: pinterest
  linkedin: linkedin
width: 20px
radius: 3px
print_css: ''
facebook_app_id: '43564564356456435634635463456'
node_field: false
